spring:
  application:
    name: "configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
         uri: "https://github.com/Amansinghkandwal/desingXBank-config.git"
         default-label: main
         timeout: 5
         clone-on-start: true
         force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      readiness-state:
        enabled: true
      liveness-state:
        enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45ASFSFGRHTBSTHBGFHR253Y7BXGF"
server:
  port: 8071
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"